# Generated by Django 4.1.1 on 2022-09-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='designations',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='display_order',
        ),
    ]
